apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i3c7jwl8z-java-quarkus
  janus-idp.io/tekton: i3c7jwl8z-java-quarkus
  backstage.io/kubernetes-id: i3c7jwl8z-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i3c7jwl8z-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
